### ISSUE TITLE
Wheel Odometry Fusion

### ISSUE THREAD

**Issue by samsonli** [pietroglyph/ftc265#1]
Hi, our team is attempting to try and use the T265 Camera in conjunction with dead tracking wheels. 
However, we just can't understand [`T265Camera.sendOdometry(velX, velY)`](https://github.com/pietroglyph/ftc265/blob/00c09a3cab1486696ac6d44df9920f4d4d368573/lib/src/main/java/com/spartronics4915/lib/T265Camera.java#L187) as well as its relationship with the `RelocalizationMap`.
We have also noticed a comment saying that "[`Only 1 odometry sensor is supported for now (index 0)`](https://github.com/pietroglyph/ftc265/blob/00c09a3cab1486696ac6d44df9920f4d4d368573/lib/src/main/java/com/spartronics4915/lib/T265Camera.java#L189)". Does this mean that it is unable to send the data from two encoders; it can only use one wheel?

Any help is appreciated.

Edit: Not the RelocalizationMap, I meant the [calibration file](https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#wheel-odometry-calibration-file-format)

**Comment by pietroglyph** [comment]
As many wheels as you have are supported; the trick is to use forward kinematics to convert your wheel's velocities into whole-robot velocities. `velX` and `velY` are the X and Y components of the whole-robot velocity in the robot coordinate frame (i.e. +X points forwards from the center of the robot, and +Y points to the left from the perspective of an observer standing behind the robot.)

The relocalization map is almost entirely unrelated to this; it allows you to map a scene and import that map for use later.

**Comment by samsonli** [comment]
What's the use of the [calibration file](https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#wheel-odometry-calibration-file-format)?

**Comment by pietroglyph** [comment]
That file is filled in by ftc265 for you based on the information you pass to the `T265Camera` constructor. If you [read the native code](https://github.com/pietroglyph/ftc265/blob/a999dc21e65b03dacbf4ced03c579d725934195c/lib/src/main/cpp/t265wrapper.cpp#L47) you can see how this works.

**Comment by samsonli** [comment]
Thanks, that made it work.
