### ISSUE TITLE
Camera outputs NaN, Confidence: Failed

### ISSUE THREAD

**Issue by samsonli** [pietroglyph/ftc265#2]
Recently we've been having a few occurrences of the camera outputting 
```
Position: (NaN, NaN, 0.0)
Velocity: (NaN, NaN, NaN)
Confidence: Failed
```
This resolved itself after some time (not sure how), but now it's back again.

We have tried unplugging and replugging the camera.
The first time we ran the program after that we got the "No device attached" exception on init.
The second time and onwards, we did not get the exception but it continued outputting the failed data (Even after we unplugged the camera during the program).

Any ideas? Thanks.

**Comment by pietroglyph** [comment]
Has this ever happened while you were not fusing encoder odometry?

**Comment by samsonli** [comment]
No, so far it has only happened when fusing encoder odometry.

**Comment by pietroglyph** [comment]
Ok, it sounds like this is an odometry issue. Please make sure that you're only sending valid velocity measurements, that the measurement covariance that you pass in the `T265Camera` constructor is valid, and that the robot to camera transform you also pass there is valid.

If you have the code you're using to construct and send encoder data on GitHub then I can take a look and tell you if I see any issues.
