### ISSUE TITLE
T265 not detected by Robot controller app

### ISSUE THREAD

**Issue by AJmods** [pietroglyph/ftc265#3]
I'm trying to connect the T265 to the robot phone, and theres a pop up saying "allow FTC app to use this device" but the configuration menu in the robot controller app won't detect the T265

I'm using a rooted Samsung S5 with android 5.1.1.  I'm forcing the libaries to run on SDK version 22 (instead of min version of 24).  

What is the issue?  Is it the S5, the Android 5.1.1, forcing the libary to run on SDK ver 22, or (hopefully) something else entirely.

How did you guys connect the T255 to the robot phone?

**Comment by pietroglyph** [comment]
I might be misunderstanding (please let me know if I am), but if you mean that the T265 doesn't show up under the list of hardware enumerated by the FTC SDK then this is intended behavior. To access the pose stream you only need to instantiate a `T265Camera` somewhere in your code, and it will automatically detect and set up the camera. No other configuration is needed.

**Comment by AJmods** [comment]
Update: I tried what you said, and ran the testT265 opmode, sadly, the robot phone crashed.  The logs said:

> java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH 

Discovered that the cause was me forcing this library to run on SDK verison 22 on my Galaxy S5 and not SDK verison 24, the minimum SDK version of the library.

So to anyone reading this, make sure to run this on Android 7.0.0 or higher instead of forcing it to run on a lower OS (like Android 5.1.1 on a Galaxy S5, for example).

Tried this on an **unrooted** Moto G Play and the TestT265 opmode was able to detect the T265 and track it's position.  (Note: rotation was not accurate at all, but the rev IMU would be able substitute for it).

**Comment by pietroglyph** [comment]
Good to hear that it worked out for you on an unrooted phone. Unfortunately we're limited to to a minimum API version of 24 by librealsense.

The camera yaw should definitely not be wrong—it was always quite accurate for me (even when the T265's scene was occluded.) If it isn't right the translation component of the pose estimate will also probably not be correct. It might be useful to check and see if your T265 works better in a different room, or in the same room when connected to a computer running Realsense Viewer.

**Comment by AJmods** [comment]
I put the T265 on my teams robot and it works (rotation is accurate when the thing is on a bot, not when your holding it with a hand).  

Anyway this is working amazing well, it's so much easier to work with compared to odometry (and more accurate too).  This is an amazing tool.
