### ISSUE TITLE
Failed to resolve dependency (likely not ftc265 specific)

### ISSUE THREAD

**Issue by samsonli** [pietroglyph/ftc265#4]
I'm trying to get another project to use ftc265 however I keep getting this error
`Failed to resolve: com.spartronics4915.lib:ftc265:2.0.1`
It worked on a previous project though.
I have tried reordering the dependencies as well as commenting out the annotationProcessor.

![image](https://user-images.githubusercontent.com/3174342/92425579-80d50f80-f13c-11ea-9447-76f85af88e95.png)

**Comment by pietroglyph** [comment]
Sorry about taking a while to respond to this... The FTCLib transitive dependency was broken, but it should be fixed now. It would be great if you could confirm that resolving the dep works now.
